### ISSUE TITLE
Please allow an option to skip X samples at the beginning and end

### ISSUE THREAD

**Issue by keith-horton** [microsoft/Network-Performance-Visualization#24]
When viewing results we will often find that some of the initial data and tail data has outliers which are uninteresting for that specific analysis. This usually isn't known apriori - it's usually discovered after a scenario is run and we look at the data. It would be great to have an option to exclude X (samples or time-blocks) from the beginning and the ending of the samples.

**Comment by lgonzalez876** [comment]
Added warmup and cooldown arguments to NetPerfVis. These parameters only have effect on ctsTraffic and latte, since these are the only two whose raw data consists of individual, chronologically ordered samples.
