### ISSUE TITLE
Parse-Files : Index operation failed; the array index evaluated to null.

### ISSUE THREAD

**Issue by PaoloPx** [microsoft/Network-Performance-Visualization#35]
Can you please add some basic  instructions, specifically on the format required for input files? 
_"Parse-Files : Index operation failed; the array index evaluated to null."_ Is not a particularly illuminating error message.
Thanks

**Comment by tmolenh** [comment]
Hi, please share the input file(s) that give you this error.

Thanks,
Tom

**Comment by PaoloPx** [comment]
Hi Tom,    it was really pretty basic.. I saved the csv files in the same folder where the cts executable and pdb files were. It seems it tried to parse the .PDB, and did not digest it well.


New-NetworkVisualization -CTStraffic -BaselineDir C:\Users\pp\Desktop\#TEMP\cts -SavePath C:\Users\pp\Desktop\#TEMP\pp1.xlsx -InnerPivot Sessions 
Parse-Files : Index operation failed; the array index evaluated to null.At C:\Program Files\WindowsPowerShell\Modules\Network-Performance-Visualization\2021.1.24.1\Network-Performance-Visualization.psm1:142 char:20+     $baselineRaw = Parse-Files -Tool $tool -DirName $BaselineDir+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : InvalidOperation: (:) [Parse-Files], RuntimeException    + FullyQualifiedErrorId : NullArrayIndex,Parse-Files

In that folder I only have clientstatus.csv (attached), and the ctsPerf.pdb file from the latest release of cts.

BTW, if I remove the pdb file then it completes successfully, but the excel file has no content.

So, with me being somewhat retarded, I supposed I would need a specific input format to get this to work, and I was wondering what that would be.
Many thanks,    Paolo

    On Thursday, February 18, 2021, 11:10:18 AM GMT+7, Tom Molenhouse <notifications@github.com> wrote:  
 
 


Hi, please share the input file(s) that give you this error.

Thanks,
Tom

**Comment by tmolenh** [comment]
https://github.com/microsoft/Network-Performance-Visualization/commit/cc6009c5b90d7acb54937da3178063a09783c7c1 adds a better error message when an invalid file CTSTraffic file is parsed. However, it does not address the situation you brought up where some files (.pdb) should obviously just be skipped.

**Comment by PaoloPx** [comment]
yes, thanks for answering.
Dunno, if this were one of my scripts I would put a  try()/catch() around line 180 (get-content), so you can trap import errors, and just look for files with a CSV extension instead than trying to gobble whatever is in that folder. it is not generic, but maybe it does not need to be so.
Anyway, thanks again.
Paolo
On Tuesday, February 23, 2021, 10:07:35 AM GMT+7, Tom Molenhouse <notifications@github.com> wrote:
 
 
 


cc6009c adds a better error message when an invalid file CTSTraffic file is parsed. However, it does not address the situation you brought up where some files (.pdb) should obviously just be skipped.
