### ISSUE TITLE
Divide by 0 error if standard deviation is 0

### ISSUE THREAD

**Issue by amao9098** [microsoft/Network-Performance-Visualization#42]
Divide by 0 error if standard deviation is 0 in data processing. 

Specific line:
https://github.com/microsoft/Network-Performance-Visualization/blob/ca7d46f91b2620704ae2683bafa97cfec8bb69d4/DataProcessor.psm1#L283

**Comment by lgonzalez876** [comment]
Latest change adds a check to make sure stdDev not equal to 0 before calculating skewness and kurtosis
